spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.61.20.91:3306/ISMS
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level: 
    com.isms.ismsbackend.dao: debug

server:
  port: 8081